book_collection/config/routes.rb
Rails.application.routes.draw do

  resources :books do
  	member do
  		get :delete
  	end
  end
  #get 'books/index'
  #get 'books/show'
  #get 'books/new'
  #get 'books/edit'
  #get 'books/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_collection/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book_collection/app/models/book.rb
class Book < ApplicationRecord
end

book_collection/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

book_collection/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
  end

  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)

    if @book.save
      flash[:notice]="New book has been added successfully"
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
     @book=Book.find(params[:id])

    if @book.update_attributes(book_params)
      flash[:notice]="Book has been updated successfully"
      redirect_to(book_path(@book))
    else
      render('edit')
    end
  end

  def delete
    @book=Book.find(params[:id])
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    flash[:notice]="Book '#{@book.title}' deleted successfully."
    redirect_to(books_path)
  end

  private 

  def book_params
    params.require(:book).permit(:title,:genre,:author,:created_at)
  end
end

book_collection/app/helpers/application_helper.rb
module ApplicationHelper
end

book_collection/app/helpers/books_helper.rb
module BooksHelper
end

book_collection/app/views/books/delete.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>

    <p class="reference-name"><%= f.object.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

book_collection/app/views/books/edit.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Update Book</h2>

  <%= form_for(@book) do |f| %>

  	<table summary="Subject form fields">
    <tr>
      <th>Title</th>
      <td><%= f.text_field(:title) %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= f.select :genre, [ 'Mystery', 'Romance', 'Fantasy', 'Sci-Fi', 'Other' ], :prompt => 'Select One' %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= f.text_field(:author) %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= f.datetime_select(:created_at, :order =>[:month,:day,:year]) %></td>
    </tr>
  </table>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

book_collection/app/views/books/index.html.erb
<% @page_title="All Books" %>
<% if !flash[:notice].blank? %>
	<div class="notice">
		<%=
		 flash[:notice] %>
	</div>
<% end %>

<div class="subjects index">
  <h2>Books</h2>

  <%= link_to("Add New Book", new_book_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>Title</th>
      <th>Genre</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.genre %></td>
      <td><%= book.author %></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), :class => 'action show') %>
        <%= link_to("Edit", edit_book_path(book), :class => 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

book_collection/app/views/books/new.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>

  	<table summary="Subject form fields">
    <tr>
      <th>Title</th>
      <td><%= f.text_field(:title) %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= f.select :genre, [ 'Mystery', 'Romance', 'Fantasy', 'Sci-Fi', 'Other' ], :prompt => 'Select One' %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= f.text_field(:author) %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= f.datetime_select(:created_at, :order =>[:month,:day,:year]) %></td>
    </tr>
  </table>

    <div class="form-buttons">
      <%= f.submit("Add Book") %>
    </div>

  <% end %>
</div>

book_collection/app/views/books/show.html.erb
<% if !flash[:notice].blank? %>
	<div class="notice">
		<%= flash[:notice] %>
	</div>
<% end %>
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Book Details</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

book_collection/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>